### ISSUE TITLE
Pluto notebook

### ISSUE THREAD

**Issue by ntrh0** [panifie/Vindicta.jl#18]
Write a pluto notebook to showcase features

**Comment by femtotrader** [comment]
I'd be pleased to help on this when I will understand PingPong.jl features.

Here is what I did to have a Pluto notebook running with PingPong and a Docker configuration.


I created a `custom\Dockerfile` file like so

```
FROM docker.io/panifie/pingpong-precomp-interactive
RUN julia -e 'using Pkg; Pkg.add("Pluto")' 
ENTRYPOINT [ "julia", "-e", "using Pluto; Pluto.run(; host=\"0.0.0.0\")"]
```

I create a `docker-compose.yml` like so

```
services:
  pingpong:
    #image: pingpong-precomp-interactive
    build:
      context: custom
      dockerfile: Dockerfile
    #restart: unless-stopped
    ports:
      - 1234:1234
```


I ran this container using 

    docker compose up

I looked at logs, browsed to http://127.0.0.1:1234/?secret=XXXXXX and created a new notebook with the following content

```
begin
    import Pkg
    # activate a temporary environment
    #Pkg.activate(mktempdir())
	Pkg.activate("/pingpong")
	#Pkg.add("Term")
	Pkg.instantiate()
end
```

unfortunately 

    using PingPong

raised

    ArgumentError: Package PingPong not found in current path.

    - Run `import Pkg; Pkg.add("PingPong")` to install the PingPong package.
